// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYEDGqwWSpwBv1nez8CX_7SVPPNhjla1w',
    appId: '1:461715418790:web:17ec12897c7f0b4f148e67',
    messagingSenderId: '461715418790',
    projectId: 'compus-app',
    authDomain: 'compus-app.firebaseapp.com',
    storageBucket: 'compus-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkNlGrFt2OS35ckXEEifjbhEVLqwIPRe8',
    appId: '1:461715418790:android:515edf380c069ea1148e67',
    messagingSenderId: '461715418790',
    projectId: 'compus-app',
    storageBucket: 'compus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxtSdmyWKotc4N_e_qFi0b_0pUOK9ZxnQ',
    appId: '1:461715418790:ios:4410daa7fc2d9781148e67',
    messagingSenderId: '461715418790',
    projectId: 'compus-app',
    storageBucket: 'compus-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxtSdmyWKotc4N_e_qFi0b_0pUOK9ZxnQ',
    appId: '1:461715418790:ios:4410daa7fc2d9781148e67',
    messagingSenderId: '461715418790',
    projectId: 'compus-app',
    storageBucket: 'compus-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYEDGqwWSpwBv1nez8CX_7SVPPNhjla1w',
    appId: '1:461715418790:web:b4e025a12282f20b148e67',
    messagingSenderId: '461715418790',
    projectId: 'compus-app',
    authDomain: 'compus-app.firebaseapp.com',
    storageBucket: 'compus-app.firebasestorage.app',
  );
}
